### ISSUE TITLE
Requesting for adding the library as a submodule of dt benchmarks

### ISSUE THREAD

**Issue by Kurt-Liuhf** [LucasBoTang/MIP_Decision_Tree#5]
Hi, thank you for making this awesome library. I am building a library of DT/GBDT benchmarks and I wonder if I can add your library to my own repository as a submodule. The repository coming to be released is not for business usage.
Thanks again and looking forward to your reply at your earliest convenience.

**Comment by LucasBoTang** [comment]
Hi, I am honored to make a contribution. You can use my code for sure. All you need to do is to give a reference in the right place.
